### ISSUE TITLE
Versioning Changes

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-technical-manual#17]
Current doc: https://github.com/OpenVoiceOS/ovos-technical-manual/blob/master/docs/versioning.md

I would propose we follow the [Python spec](https://packaging.python.org/en/latest/specifications/version-specifiers/) and use `dev` for the alpha channel and `a` or `b` for the beta channel (a is consistent with what we have been doing, I think `b` would be more logical).

This also makes sense that `dev` releases follow the `dev` branch. Open to input but I think we do need some release versioning that identifies releases from the `testing` branch differently than the `dev` branch.

**Comment by builderjer** [comment]
With this, I think we need a good contributions guide.  Things that must be there in order for a PR to be looked at.  Something for users that want to contribute.

**Comment by NeonDaniel** [comment]
Possibly an integration guide as well. To summarize some conversation on Matrix regarding the current implementation:
- Integrators can pin the `testing` branch for validation
- Mixing pre-release identifiers is discouraged per the linked Python spec, so differentiating `dev` from `testing` with version strings is not as simple as my initial proposal
- In *most* cases, the code on the `testing` branch will correspond to a specific `alpha` release

**Comment by mikejgray** [comment]
@NeonDaniel We can probably close this now that OVOS is following semver?

**Comment by NeonDaniel** [comment]
> @NeonDaniel We can probably close this now that OVOS is following semver?

I think the linked doc is outdated for different reasons now, but relevant discussion is probably best continued in https://github.com/OpenVoiceOS/ovos-releases/issues/5
